version: "3"

services:  
  nginx:  
    image: nginx:1.17.3  
    container_name: nginx-site  
    ports: ["0.0.0.0:80:80" ,"0.0.0.0:443:443"]
    volumes: ["~/docker-data/nginx/conf.d/:/etc/nginx/conf.d:ro","~/docker-data/nginx/logs:/var/log/nginx","~/docker-data/nginx/ssl:/ssl:ro","~/docker-data/nginx/site:/site:ro","~/docker-data/certbot/conf:/etc/letsencrypt","~/docker-data/certbot/www:/var/www/certbot"]  
    restart: unless-stopped
  certbot:  
    image: certbot/certbot  
    container_name: certbot  
    volumes: ["~/docker-data/certbot/conf:/etc/letsencrypt","~/docker-data/certbot/www:/var/www/certbot"]  
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  
    restart: unless-stopped